In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('Deliveries IPL 2020.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1216492,1,MI,CSK,1,1,RG Sharma,Q de Kock,DL Chahar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
1,1216492,1,MI,CSK,1,2,RG Sharma,Q de Kock,DL Chahar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2,1216492,1,MI,CSK,1,3,Q de Kock,RG Sharma,DL Chahar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
3,1216492,1,MI,CSK,1,4,Q de Kock,RG Sharma,DL Chahar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
4,1216492,1,MI,CSK,1,5,Q de Kock,RG Sharma,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [18]:
#Calculate the runs per ball of each batsman
player_runs = df.groupby(['batsman'])['batsman_runs'].sum().sort_values()
player_balls = df.groupby(['batsman']).size()
rpb = player_runs/player_balls*100

#Calculate the number of dismissals for each batsman
outs = df['player_dismissed'].value_counts()

#Store runs per ball and number of dismissals in a dictionary
bat_dict = {}
for player in rpb.to_dict():
    try:
        bat_dict[player] = (rpb[player], outs[player])
    except:
        bat_dict[player] = (rpb[player], 0)
bat_dict

{'AB de Villiers': (153.81944444444443, 3),
 'AD Russell': (168.91891891891893, 1),
 'AJ Finch': (106.82730923694778, 7),
 'AJ Tye': (100.0, 0),
 'AM Rahane': (101.8018018018018, 5),
 'AR Patel': (116.66666666666667, 4),
 'AS Rajpoot': (100.0, 0),
 'AS Yadav': (153.38983050847457, 0),
 'AT Rayudu': (125.44169611307422, 3),
 'Abdul Samad': (176.47058823529412, 2),
 'Abhishek Sharma': (116.36363636363636, 1),
 'Anrich Nortje': (100.0, 0),
 'Arshdeep Singh': (0.0, 0),
 'BA Stokes': (141.58415841584159, 3),
 'CH Gayle': (130.57851239669424, 3),
 'CH Morris': (178.94736842105263, 2),
 'CJ Jordan': (81.3953488372093, 0),
 'CV Varun': (60.0, 1),
 'Carey': (118.5185185185185, 0),
 'Cottrell': (0.0, 0),
 'D Padikkal': (121.28205128205127, 6),
 'DA Warner': (136.72055427251732, 4),
 'DJ Bravo': (140.0, 1),
 'DJ Hooda': (136.0, 0),
 'DL Chahar': (63.63636363636363, 0),
 'DS Kulkarni': (150.0, 0),
 'DW Steyn': (50.0, 0),
 'Deshpande': (190.9090909090909, 0),
 'EJG Morgan': (137.5, 0),
 'F du Plessis': (140.88050314465409, 0),
 'GJ Maxwell': (99.14529914529915, 0),
 'Gurkeerat Singh': (86.58536585365853, 0),
 'HH Pandya': (168.48484848484847, 3),
 'HV Patel': (126.4367816091954, 1),
 'I Udana': (166.66666666666669, 0),
 'Imran Tahir': (130.0, 0),
 'Ishan Kishan': (146.45892351274787, 1),
 'J Archer': (172.1311475409836, 0),
 'J Bairstow': (122.07357859531773, 0),
 'JC Buttler': (146.63677130044843, 1),
 'JD Unadkat': (75.0, 0),
 'JDS Neesham': (118.75, 0),
 'JJ Bumrah': (166.66666666666669, 0),
 'JL Pattinson': (125.0, 0),
 'JO Holder': (128.33333333333334, 1),
 'Jagadeesan': (113.79310344827587, 0),
 'K Ahmed': (0.0, 0),
 'K Gowtham': (161.53846153846155, 0),
 'K Rabada': (112.00000000000001, 1),
 'KA Pollard': (181.8181818181818, 4),
 'KD Karthik': (129.23076923076923, 5),
 'KH Pandya': (128.23529411764707, 2),
 'KK Nair': (123.07692307692308, 1),
 'KL Nagarkoti': (70.96774193548387, 1),
 'KL Rahul': (127.22323049001815, 9),
 'KM Jadhav': (95.38461538461539, 1),
 'KS Williamson': (133.89830508474577, 1),
 'Kartik Tyagi': (80.0, 0),
 'Kuldeep Yadav': (61.904761904761905, 0),
 'L Ferguson': (150.0, 0),
 'M Ali': (85.71428571428571, 0),
 'M Ashwin': (133.33333333333331, 0),
 'M Lomror': (115.68627450980394, 0),
 'M Vijay': (76.19047619047619, 1),
 'MA Agarwal': (155.71428571428572, 5),
 'MK Pandey': (119.24119241192412, 3),
 'MP Stoinis': (147.08333333333334, 5),
 'MS Dhoni': (118.34319526627219, 2),
 'Mandeep Singh': (122.50000000000001, 2),
 'Mohammad Nabi': (142.85714285714286, 0),
 'Mohammed Shami': (66.66666666666666, 1),
 'Mohammed Siraj': (121.42857142857142, 1),
 'Mujeeb Ur Rahman': (50.0, 0),
 'N Naik': (50.0, 0),
 'N Pooran': (164.95726495726495, 3),
 'N Rana': (139.91935483870967, 2),
 'N Saini': (100.0, 0),
 'NM Coulter-Nile': (166.66666666666669, 1),
 'P Kumar': (0.0, 0),
 'P Shaw': (142.5, 0),
 'PJ Cummins': (128.0701754385965, 0),
 'Philippe': (105.12820512820514, 0),
 'Prabhsimran Singh': (66.66666666666666, 0),
 'Prasidh Krishna': (50.0, 0),
 'Praveen Dubey': (53.84615384615385, 0),
 'Priyam Garg': (113.91304347826087, 0),
 'Q de Kock': (140.11142061281336, 6),
 'R Ashwin': (119.35483870967742, 0),
 'R Parag': (113.1578947368421, 1),
 'R Singh': (110.00000000000001, 0),
 'R Tewatia': (135.67567567567568, 4),
 'RA Jadeja': (166.66666666666669, 1),
 'RA Tripathi': (127.77777777777777, 4),
 'RD Chahar': (50.0, 0),
 'RD Gaikwad': (123.25581395348837, 2),
 'RG Sharma': (127.16981132075472, 4),
 'RR Pant': (108.28025477707006, 5),
 'RV Uthappa': (120.0, 2),
 'Rashid Khan': (112.90322580645163, 3),
 'Ravi Bishnoi': (63.63636363636363, 0),
 'S Curran': (135.25179856115108, 0),
 'S Dhawan': (144.70588235294116, 6),
 'S Dube': (122.64150943396226, 4),
 'S Gopal': (100.0, 0),
 'S Hetmyer': (150.0, 0),
 'S Nadeem': (100.0, 0),
 'SA Yadav': (120.40816326530613, 4),
 'SN Khan': (113.79310344827587, 1),
 'SN Thakur': (60.0, 0),
 'SP Goswami': (0.0, 2),
 'SP Narine': (140.69767441860466, 5),
 'SPD Smith': (124.89451476793249, 3),
 'SR Watson': (119.6, 6),
 'SS Iyer': (121.14014251781472, 4),
 'SS Tiwary': (133.76623376623377, 1),
 'SV Samson': (163.67521367521368, 2),
 'Sandeep Sharma': (85.71428571428571, 0),
 'Shahbaz Ahmed': (100.0, 0),
 'Shivam Mavi': (83.33333333333334, 0),
 'Shubman Gill': (118.1081081081081, 1),
 'Simran Singh': (157.14285714285714, 0),
 'T Banton': (85.71428571428571, 1),
 'T Curran': (133.8709677419355, 0),
 'T Natarajan': (60.0, 0),
 'TA Boult': (0.0, 1),
 'UT Yadav': (0.0, 1),
 'V Kohli': (120.35623409669212, 2),
 'V Shankar': (100.8130081300813, 1),
 'VR Aaron': (11.11111111111111, 0),
 'WP Saha': (136.30573248407643, 0),
 'Washington Sundar': (119.35483870967742, 1),
 'YBK Jaiswal': (95.23809523809523, 1),
 'YS Chahal': (20.0, 1)}

In [19]:
#Calculate number of wickets taken for each bowler
wickets = df[df['player_dismissed'].notnull()]['bowler'].value_counts()

#Calculate bowler economy rate
bowler_runs = df.groupby(['bowler'])['batsman_runs'].sum().sort_values()
bowler_balls = df.groupby(['bowler']).size()
bowler_rpb = bowler_runs/bowler_balls*100


ball_dict = {}
for player in bowler_rpb.to_dict():
    try:
        ball_dict[player] = (bowler_rpb[player], wickets[player])
    except:
        ball_dict[player] = (bowler_rpb[player], 0)

print(ball_dict)

{'A Mishra': (120.6896551724138, 0), 'A Zampa': (137.87878787878788, 1), 'AD Russell': (150.45871559633028, 2), 'AJ Finch': (104.16666666666667, 1), 'AJ Tye': (188.0, 0), 'AR Patel': (100.67114093959732, 0), 'AS Rajpoot': (162.83185840707966, 0), 'Abdul Samad': (216.66666666666666, 0), 'Abhishek Sharma': (148.33333333333334, 1), 'Ankit Sharma': (151.11111111111111, 1), 'Anrich Nortje': (136.1413043478261, 15), 'Arshdeep Singh': (140.55944055944056, 1), 'Arshdeep Singh ': (115.99999999999999, 0), 'Avesh Khan': (164.0, 0), 'BA Stokes': (155.3191489361702, 0), 'Basil Thampi': (200.0, 0), 'CH Gayle': (100.0, 0), 'CH Morris': (100.51546391752578, 2), 'CJ Green': (141.1764705882353, 0), 'CJ Jordan': (139.9103139013453, 2), 'CV Varun': (117.54966887417217, 6), 'Cottrell': (130.95238095238096, 1), 'DA Warner': (50.0, 0), 'DJ Bravo': (132.8125, 0), 'DJ Hooda': (150.0, 0), 'DL Chahar': (123.2484076433121, 5), 'DS Kulkarni': (100.0, 0), 'DW Steyn': (172.97297297297297, 0), 'Daniel Sams': (141.55844155844156, 0), 'Deshpande': (171.02803738317758, 0), 'GJ Maxwell': (136.29032258064515, 1), 'HH Pandya': (180.0, 0), 'HV Patel': (122.44897959183673, 2), 'Harpreet Singh': (160.0, 0), 'Hazlewood': (105.0, 0), 'I Udana': (155.6818181818182, 2), 'Imran Tahir': (115.15151515151516, 1), 'Ishan Kishan': (113.04347826086956, 1), 'J Archer': (106.6465256797583, 6), 'JD Unadkat': (155.3191489361702, 2), 'JDS Neesham': (159.34065934065933, 0), 'JJ Bumrah': (110.08174386920982, 13), 'JL Pattinson': (145.32710280373834, 3), 'JO Holder': (130.20833333333331, 7), 'K Ahmed': (154.02298850574712, 3), 'K Gowtham': (178.72340425531914, 0), 'K Rabada': (135.96938775510205, 10), 'KA Pollard': (131.85185185185185, 1), 'KD Karthik': (100.0, 0), 'KH Pandya': (63.1578947368421, 0), 'KL Nagarkoti': (146.45161290322582, 0), 'KS Williamson': (200.0, 0), 'KV Sharma': (141.2280701754386, 1), 'Kartik Tyagi': (151.5151515151515, 0), 'Kuldeep Yadav': (120.27027027027026, 0), 'L Ferguson': (117.21311475409837, 4), 'L Ngidi': (152.08333333333331, 2), 'M Ali': (129.03225806451613, 0), 'M Ashwin': (123.22274881516589, 7), 'M Santner': (132.5, 0), 'M Ur Rahman': (172.0, 0), 'M Ur Rahman ': (162.5, 0), 'MEK Hussey': (95.83333333333334, 0), 'MJ Guptill': (100.0, 0), 'MK Pandey': (118.5185185185185, 2), 'MP Stoinis': (155.61797752808988, 7), 'MR Marsh': (150.0, 0), 'Mohammad Nabi': (76.92307692307693, 0), 'Mohammed Shami': (139.59537572254334, 3), 'Mohammed Siraj': (133.13253012048193, 5), 'Monu ': (87.5, 0), 'N Rana': (169.23076923076923, 0), 'N Saini': (126.98961937716263, 3), 'NM Coulter-Nile': (120.98765432098766, 3), 'P Kumar': (111.90476190476191, 1), 'PJ Cummins': (127.38853503184713, 5), 'PP Chawla': (154.0983606557377, 1), 'Prasidh Krishna': (145.9016393442623, 0), 'Prasidh Krishna ': (154.34782608695653, 2), 'Praveen Dubey': (150.0, 0), 'Q de Kock': (121.24999999999999, 1), 'R Ashwin': (126.64473684210526, 7), 'R Parag': (192.30769230769232, 0), 'R Tewatia': (114.13043478260869, 1), 'RA Jadeja': (145.16129032258064, 2), 'RD Chahar': (137.74193548387098, 3), 'Rashid Khan': (88.11881188118812, 11), 'Ravi Bishnoi': (113.25301204819279, 5), 'S Curran': (129.36507936507937, 1), 'S Dube': (139.2156862745098, 1), 'S Gopal': (142.0875420875421, 2), 'S Kaul': (244.0, 1), 'S Nadeem': (122.96296296296296, 4), 'SN Thakur': (136.08247422680412, 1), 'SP Narine': (132.3008849557522, 2), 'Sandeep Sharma': (119.57831325301204, 6), 'Sandeep Warrier': (147.61904761904762, 0), 'Shahbaz Ahmed ': (116.21621621621621, 2), 'Shivam Mavi': (134.640522875817, 0), 'T Curran': (176.99115044247787, 0), 'T Natarajan': (126.79900744416874, 7), 'TA Boult': (138.39285714285714, 8), 'UT Yadav': (175.55555555555554, 0), 'V Shankar': (87.65432098765432, 1), 'VR Aaron': (155.55555555555557, 0), 'Washington Sundar': (100.0, 3), 'YS Chahal': (117.36526946107784, 8)}

In [23]:
#Calculate balls bowled per match for each bowler
balls_bowled = df.groupby(['bowler']).size()
bowl_matches = df.groupby(['bowler'])['match_id'].nunique()
balls_per_match = balls_bowled/bowl_matches
balls_per_match

bowler
A Mishra             19.333333
A Zampa              22.000000
AD Russell           15.571429
AJ Finch             24.000000
AJ Tye               25.000000
                       ...
UT Yadav             22.500000
V Shankar            16.200000
VR Aaron             18.000000
Washington Sundar    19.733333
YS Chahal            22.266667
Length: 107, dtype: float64

In [24]:
#Calculate balls batted per match for each batsman
balls_batted = df.groupby(['batsman']).size()
bat_matches = df.groupby(['batsman'])['match_id'].nunique()
batted_balls_per_match = balls_batted/bat_matches
batted_balls_per_match

batsman
AB de Villiers       20.571429
AD Russell            8.222222
AJ Finch             20.750000
AJ Tye                6.000000
AM Rahane            13.875000
                       ...
VR Aaron              4.500000
WP Saha              39.250000
Washington Sundar    10.333333
YBK Jaiswal          14.000000
YS Chahal             2.500000
Length: 133, dtype: float64

# Optimization Model

In [26]:
import gurobipy as gp
from gurobipy import GRB

#Create model
m = gp.Model("superteam")


#Store list of all players
players = list(set(df['bowler'].to_list() + df['batsman'].to_list()))


team = m.addVars(players, name = "team", vtype = GRB.BINARY)
m.setObjective(sum(bat_dict[p][0]*team[p] for p in bat_dict) - sum(ball_dict[p][0]*team[p] for p in ball_dict), GRB.MAXIMIZE)

#11 players on the team
m.addConstr((sum(team[p] for p in players)) == 11)

#Must have atleast 5 bowlers
m.addConstr(sum(p[1]*team[p[0]] for p in [(p, 1) if p in ball_dict else (p, 0) for p in players]) >= 5)


#Average total overs bowled by team must be atleast 20 overs
m.addConstr(sum(balls_per_match[p]*team[p] for p in ball_dict) >= 120)

#Average total overs batted by team must be atleast 20 overs
m.addConstr(sum(batted_balls_per_match[p]*team[p] for p in bat_dict) >= 120)


#Batsmen & Bowler needs to have played atleast 3 matches
#print([bat_matches[p] >= team[p] for p in bat_dict])
m.addConstrs(team[p]*3 <= bat_matches[p] for p in bat_dict)
m.addConstrs(team[p]*3 <= bowl_matches[p] for p in ball_dict)


m.optimize()

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 244 rows, 157 columns and 744 nonzeros
Model fingerprint: 0x0cad5951
Variable types: 0 continuous, 157 integer (157 binary)
Coefficient statistics:
  Matrix range     [1e+00, 4e+01]
  Objective range  [7e-01, 2e+02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+02]
Found heuristic solution: objective 513.3857658
Presolve removed 240 rows and 73 columns
Presolve time: 0.00s
Presolved: 4 rows, 84 columns, 247 nonzeros
Variable types: 0 continuous, 84 integer (84 binary)
Found heuristic solution: objective 996.5839950

Root relaxation: objective 1.118952e+03, 4 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 1118.95210    0    2  996.58400 1118.95210  12.3%     -    0s
H    0     0                    1116.7787691 1118.95210  0.19%     -    0s

Explored 1 nodes (4 simplex iterations) in 0.05 seconds (0.00 work units)
Thread count was 8 (of 8 available processors)

Solution count 3: 1116.78 996.584 513.386

Optimal solution found (tolerance 1.00e-04)
Best objective 1.116778769053e+03, best bound 1.116778769053e+03, gap 0.0000%

This is the starting lineup of the optimal team
CH Morris
JO Holder
SV Samson
SP Narine
N Pooran
AB de Villiers
J Archer
S Hetmyer
Rashid Khan
MA Agarwal
AS Yadav

In [34]:
print('\nThis is the starting lineup of the optimal team:\n')
for p in players:
    if team[p].X == 1:
        print(p)

This is the starting lineup of the optimal team:

CH Morris
JO Holder
SV Samson
SP Narine
N Pooran
AB de Villiers
J Archer
S Hetmyer
Rashid Khan
MA Agarwal
AS Yadav